name: Archive Data

on:
  schedule:
    - cron: '*/30 * * * *'  # Runs every 30 minutes

jobs:
  run-archive-data:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12.1'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run archive_data.py
        env:
          AZ511_API_KEY: ${{ secrets.AZ511_API_KEY }}  
          DB_HOST: ${{ secrets.DB_HOST }} 
          DB_USER: ${{ secrets.DB_USER }}  
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_NAME: ${{ secrets.DB_NAME }} 
        run: python archieve_data.py
